const menuButton=document.querySelector('.menu-toggle');
const mobileMenu=document.querySelector('.mobile-menu');
if(menuButton&&mobileMenu){menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));mobileMenu.hidden=open;});mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.hidden=true;menuButton.setAttribute('aria-expanded','false');}));}
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();

const revealEls=document.querySelectorAll('.reveal');
if('IntersectionObserver' in window){const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target);}});},{threshold:.12});revealEls.forEach(el=>revealObserver.observe(el));}else{revealEls.forEach(el=>el.classList.add('visible'));}

const prefersReduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const metricValues=[...document.querySelectorAll('.metric-value')];
const animateMetric=el=>{if(el.dataset.animated==='true')return;el.dataset.animated='true';const target=Number(el.dataset.target||0);const suffix=el.dataset.suffix||'';if(prefersReduced){el.textContent=`${target}${suffix}`;return;}const duration=1450;const start=performance.now();const step=now=>{const p=Math.min((now-start)/duration,1);const eased=1-Math.pow(1-p,3);el.textContent=`${Math.round(target*eased)}${suffix}`;if(p<1)requestAnimationFrame(step);};requestAnimationFrame(step);};
if('IntersectionObserver' in window&&!prefersReduced){metricValues.forEach(el=>{el.textContent=`0${el.dataset.suffix||''}`;});const metricObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){animateMetric(entry.target);metricObserver.unobserve(entry.target);}});},{threshold:.4});metricValues.forEach(el=>metricObserver.observe(el));}else{metricValues.forEach(animateMetric);}

document.querySelectorAll('[data-back-to-top]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();window.scrollTo({top:0,left:0,behavior:prefersReduced?'auto':'smooth'});history.replaceState(null,'',window.location.pathname+window.location.search);}));

const slider=document.getElementById('projectSlider');const progress=document.getElementById('sliderProgress');const currentLabel=document.getElementById('sliderCurrent');const dots=[...document.querySelectorAll('.slider-dot')];let autoSlide=null;let isDown=false,startX=0,scrollStart=0;
const gap=()=>slider?parseFloat(getComputedStyle(slider).columnGap||getComputedStyle(slider).gap||0):0;const distance=()=>{const card=slider?.querySelector('.project-card');return card?card.getBoundingClientRect().width+gap():0;};const count=()=>slider?.querySelectorAll('.project-card').length||0;const indexNow=()=>{const d=distance()||1;return Math.min(count()-1,Math.max(0,Math.round((slider?.scrollLeft||0)/d)));};
const updateSlider=()=>{if(!slider)return;const idx=indexNow();if(currentLabel)currentLabel.textContent=String(idx+1).padStart(2,'0');dots.forEach((dot,i)=>dot.classList.toggle('active',i===idx));if(progress){const total=count();const pct=total?((idx+1)/total)*100:20;progress.style.width=`${Math.max(20,pct)}%`;progress.style.transform='none';}};
const goTo=i=>{if(!slider)return;slider.scrollTo({left:distance()*i,behavior:prefersReduced?'auto':'smooth'});};const stopAuto=()=>{if(autoSlide){clearInterval(autoSlide);autoSlide=null;}};const startAuto=()=>{if(!slider||prefersReduced)return;stopAuto();autoSlide=setInterval(()=>{const idx=indexNow();goTo(idx>=count()-1?0:idx+1);},5000);};
document.querySelectorAll('.slider-btn').forEach(btn=>btn.addEventListener('click',()=>{stopAuto();const step=btn.dataset.dir==='next'?1:-1;goTo(Math.min(count()-1,Math.max(0,indexNow()+step)));startAuto();}));
dots.forEach(dot=>dot.addEventListener('click',()=>{stopAuto();goTo(Number(dot.dataset.index||0));startAuto();}));
slider?.addEventListener('scroll',updateSlider,{passive:true});window.addEventListener('resize',updateSlider);updateSlider();
slider?.addEventListener('pointerdown',e=>{if(e.target.closest('a,button'))return;isDown=true;stopAuto();startX=e.clientX;scrollStart=slider.scrollLeft;slider.classList.add('dragging');slider.setPointerCapture?.(e.pointerId);});slider?.addEventListener('pointermove',e=>{if(isDown)slider.scrollLeft=scrollStart-(e.clientX-startX);});['pointerup','pointercancel'].forEach(type=>slider?.addEventListener(type,()=>{isDown=false;slider.classList.remove('dragging');updateSlider();startAuto();}));slider?.addEventListener('mouseenter',stopAuto);slider?.addEventListener('mouseleave',startAuto);slider?.addEventListener('focusin',stopAuto);slider?.addEventListener('focusout',startAuto);slider?.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();stopAuto();const next=indexNow()+(e.key==='ArrowRight'?1:-1);goTo(Math.min(count()-1,Math.max(0,next)));startAuto();}});startAuto();
